Create database T_Ekips;

Use T_Ekips;

CREATE TABLE DEPARTAMENTO
(

	IDDEPARTAMENTO INT PRIMARY KEY IDENTITY
	,DEPARTAMENTO VARCHAR(200) NOT NULL
);

CREATE TABLE CARGO 
(
	IDCARGO INT PRIMARY KEY IDENTITY
	,CARGO VARCHAR(200) NOT NULL
);

CREATE TABLE PERMISSAO
(
	IDPERMISSAO INT PRIMARY KEY IDENTITY
	,PERMISSAO VARCHAR(200) NOT NULL
);

CREATE TABLE USUARIOVINCULADO
(
	IDUSUARIOVINCULADO INT PRIMARY KEY IDENTITY 
	,EMAIL VARCHAR(200) NOT NULL UNIQUE
	,SENHA VARCHAR(200) NOT NULL UNIQUE
	,IDPERMISSAO INT FOREIGN KEY REFERENCES PERMISSAO (IDPERMISSAO)
);

CREATE TABLE FUNCIONARIO
(
	IDFUNCIONARIO  INT PRIMARY KEY IDENTITY 
	,NOME VARCHAR(200) NOT NULL UNIQUE
	,CPF INT NOT NULL UNIQUE
	,DATANASCIMENTO DATE
	,SALARIO INT NOT NULL
	,IDDEPARTAMENTO INT FOREIGN KEY REFERENCES DEPARTAMENTO (IDDEPARTAMENTO)
	,IDCARGO INT FOREIGN KEY REFERENCES CARGO(IDCARGO)
	,IDUSUARIOVINCULADO INT FOREIGN KEY REFERENCES USUARIOVINCULADO (IDUSUARIOVINCULADO)
);

INSERT DEPARTAMENTO (DEPARTAMENTO) 
	VALUES ('Segurança')
		,('TI')
		,('LIMPEZA')
		,('ADM');

SELECT * FROM DEPARTAMENTO;

INSERT CARGO (CARGO)
	VALUES ('FAXINEIRA'),
	('ANALISTA'),
	('DESENVOLVEDOR'),
	('SEGURANÇA');

SELECT * FROM CARGO;

INSERT PERMISSAO (PERMISSAO)
	VALUES ('ADMIN'),
			('COMUM');

SELECT * FROM PERMISSAO;

INSERT USUARIOVINCULADO (EMAIL, SENHA, IDPERMISSAO)
	VALUES ('MARI_GADA@GMAIL.COM', '123456', 1)
			,('ART_HUR@SENN.NA', '98765412', 2)
			,('GARO_IRMAO@MELE.COM', '12345678', 1)
			,('MELE_IRMAO@GARO.COM', '765412', 2);
			
SELECT *FROM USUARIOVINCULADO;

INSERT FUNCIONARIO (NOME, CPF, DATANASCIMENTO, SALARIO, IDDEPARTAMENTO, IDCARGO, IDUSUARIOVINCULADO) VALUES ('ARTHUR', '12345', '12/12/1990', '999',1 ,4 ,2);
INSERT FUNCIONARIO (NOME, CPF, DATANASCIMENTO, SALARIO, IDDEPARTAMENTO, IDCARGO, IDUSUARIOVINCULADO) VALUES ('GARO', '12347', '1/12/1990', '989',2 ,2 ,3);

SELECT * FROM FUNCIONARIO

